const CACHE="bp-lyrics-b1ce68f6";
const SHELL=["/blocparty-bear-app/", "/blocparty-bear-app/a-weekend-in-the-city-lyrics/", "/blocparty-bear-app/a-weekend-in-the-city/", "/blocparty-bear-app/alpha-games-lyrics/", "/blocparty-bear-app/alpha-games/", "/blocparty-bear-app/anatomy-of-a-brief-romance-lyrics/", "/blocparty-bear-app/anatomy-of-a-brief-romance/", "/blocparty-bear-app/bloc-party-ep-lyrics/", "/blocparty-bear-app/bloc-party-ep/", "/blocparty-bear-app/blog/", "/blocparty-bear-app/complete-song-list-lyrics/", "/blocparty-bear-app/complete-songs-list/", "/blocparty-bear-app/four-lyrics/", "/blocparty-bear-app/four-more-ep-lyrics/", "/blocparty-bear-app/four-more-ep/", "/blocparty-bear-app/four/", "/blocparty-bear-app/hymns-lyrics/", "/blocparty-bear-app/hymns/", "/blocparty-bear-app/intimacy-lyrics/", "/blocparty-bear-app/intimacy/", "/blocparty-bear-app/little-thoughts-ep-lyrics/", "/blocparty-bear-app/little-thoughts-ep/", "/blocparty-bear-app/silent-alarm-lyrics/", "/blocparty-bear-app/silent-alarm/", "/blocparty-bear-app/the-high-life-ep-lyrics/", "/blocparty-bear-app/the-high-life-ep/", "/blocparty-bear-app/the-nextwave-sessions-lyrics/", "/blocparty-bear-app/the-nextwave-sessions/", "/blocparty-bear-app/welcome/", "/blocparty-bear-app/manifest.json", "/blocparty-bear-app/icon-180.png", "/blocparty-bear-app/icon-512.png"];
self.addEventListener("install",e=>{e.waitUntil(caches.open(CACHE).then(c=>c.addAll(SHELL)).then(()=>self.skipWaiting()));});
self.addEventListener("activate",e=>{e.waitUntil(caches.keys().then(k=>Promise.all(k.filter(x=>x!==CACHE).map(x=>caches.delete(x)))).then(()=>self.clients.claim()));});
async function nav(req){const c=await caches.open(CACHE);try{const f=await Promise.race([fetch(req),new Promise((_,r)=>setTimeout(()=>r(),3000))]);c.put(req,f.clone());return f;}catch(e){return (await c.match(req))||(await c.match("/blocparty-bear-app/"))||Response.error();}}
self.addEventListener("fetch",e=>{const req=e.request;if(req.method!=="GET")return;
 if(req.mode==="navigate"){e.respondWith(nav(req));return;}
 e.respondWith((async()=>{const c=await caches.open(CACHE);const hit=await c.match(req);
  const net=fetch(req).then(r=>{if(r&&(r.ok||r.type==="opaque"))c.put(req,r.clone());return r;}).catch(()=>null);
  return hit||(await net)||Response.error();})());});
